name: Run Unit Tests

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies (ImmutableGeometry)
      run: dotnet restore ImmutableGeometry
    - name: Restore dependencies (ImmutableGeometry.Test)
      run: dotnet restore ImmutableGeometry.Test
    - name: Build
      run: dotnet build --no-restore ImmutableGeometry.Test
    - name: Test
      run: dotnet test --no-build --verbosity normal ImmutableGeometry.Test

